# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CarbonCalculator
                                 A QGIS plugin
 The Carbon Calculator plugin takes point cloud and chm files, and returns an estimate of the carbon density based on different biomes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-22
        copyright            : (C) 2025 by Vitor Di Lorenzzi Nunes da Cunha
        email                : vitordilorenzzi1@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Vitor Di Lorenzzi Nunes da Cunha'
__date__ = '2025-12-22'
__copyright__ = '(C) 2025 by Vitor Di Lorenzzi Nunes da Cunha'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CarbonCalculator class from file CarbonCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tnc_carbon_calculator import CarbonCalculatorPlugin
    return CarbonCalculatorPlugin()
