# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TNC_TEST
                                 A QGIS plugin
 Plugin de teste para o projeto da TNC
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-25
        copyright            : (C) 2025 by Vitor Di Lorenzzi Nunes da Cunha
        email                : não
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Vitor Di Lorenzzi Nunes da Cunha'
__date__ = '2025-09-25'
__copyright__ = '(C) 2025 by Vitor Di Lorenzzi Nunes da Cunha'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TNC_TEST class from file TNC_TEST.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tnc_test import TNC_TESTPlugin
    return TNC_TESTPlugin()
