# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TNC_TEST
                                 A QGIS plugin
 Plugin de teste para o projeto da TNC
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-25
        copyright            : (C) 2025 by Vitor Di Lorenzzi Nunes da Cunha
        email                : não
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Vitor Di Lorenzzi Nunes da Cunha'
__date__ = '2025-09-25'
__copyright__ = '(C) 2025 by Vitor Di Lorenzzi Nunes da Cunha'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider #type: ignore
from .tnc_test_algorithm import TNC_Test_Alg_Multiband
from .tnc_biomass_v1 import TNC_Biomass_V1
from .tnc_biomass_longo import TNC_Biomass_Longo
from .tnc_biomass_amazonia_chm import TNC_Biomass_Amazonia_CHM
from .tnc_biomass_cerrado_chm import TNC_Biomass_Cerrado_CHM

class TNC_TESTProvider(QgsProcessingProvider):

    def __init__(self):
        QgsProcessingProvider.__init__(self)

    def unload(self):
        pass

    def loadAlgorithms(self):
        #self.addAlgorithm(TNC_Biomass_V1()) # (arquivo de teste, não usar)
        self.addAlgorithm(TNC_Biomass_Longo())
        self.addAlgorithm(TNC_Biomass_Cerrado_CHM())
        self.addAlgorithm(TNC_Biomass_Amazonia_CHM())

    def id(self):
        return 'tnc_test'

    def name(self):
        return 'TNC Drone Image Processing'

    def icon(self):
        return QgsProcessingProvider.icon(self)

    def longName(self):
        return self.name()
